spring:
  security:
    user:
      name: user
      password: password

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb

  h2:
    console:
      enabled: true
      path: /h2-console

server:
  port: 8081
